sway/urls.py
from django.conf.urls import patterns, url,include
from django.contrib import admin
from rest_framework.authtoken.views import obtain_auth_token
from sway import views
from sway.api import api_view
from sway.api import api_helper


admin.autodiscover()


urlpatterns=patterns('',

		url(r'^$', views.index, name='index'),
            url(r'^dancehub$', views.danceHub, name='hub'),
            url(r'^signup$', views.signup, name='signup'),
		url(r'^locations/search$', api_view.get_models_within_25, name='get_models_within_25'),
            url(r'^locations/$', views.view_locations, name='view_locations'),
            url(r'^gallery/$', views.profile_gallery, name='profile_gallery'),
		url(r'^locations/delete/(?P<id>\d+)/$', views.locaton_delete, name='locaton_delete',),
            url(r'^locations/new/$', views.add_edit_locations, name='location_add'),
		 url(r'^locations/edit/(?P<id>\d+)/$', views.add_edit_locations, name='location_edit'),
		 url(r'^categories/$', views.view_categories, name='view_categories'),
		 url(r'^categories/new/$', views.add_edit_categories, name='category_add'),
		 url(r'^categories/edit/(?P<id>\d+)/$', views.add_edit_categories, name='category_edit'),
		 url(r'^categories/delete/(?P<id>\d+)/$', views.category_delete, name='category_delete',),
		 url(r'^contact/$', views.save_contact, name='save_contact'),
		 url(r'^events/$', views.viewevents, name='events'),
		 url(r'^updateevents/$', views.updateEvent, name='updateevents'),
		 url(r'^events/editevents/(?P<id>\d+)/$', views.editevents, name='eventevents'),
		 url(r'^events/delete/(?P<id>\d+)/$', views.delete_events, name='delete_events'),
		 url(r'^addevents/$', views.addevents, name='add_events'),
		 url(r'^saveevents/$', views.saveevents, name='saveevents'),
		 url(r'^members/$', views.viewmembers, name='members'),
		 url(r'^addmembers/$', views.addmembers, name='add_members'),
	 	 url(r'^login/$', 'django.contrib.auth.views.login' , name='login'),
	 	 url(r'^logout/$', 'django.contrib.auth.views.logout' , {'next_page': '/sway/'}),
		 url(r'^savemembers/$', views.savemembers, name='savemembers'),
		 url(r'^instructors/$', views.show_instructors, name='instructors'),
		 url(r'^add_instructor/$', views.add_instructor, name='add_instructor'),
		 url(r'^save_instructor/$', views.save_instructor, name='save_instructor'),
		 url(r'^dashboard/$', views.show_dashboard, name='dashboard'),
		 url(r'^settings/$', views.show_settings, name='show_settings'),
		 url(r'^events_json/$', views.get_events_json, name='get_event_json'),
		 url(r'^loginAuth/$', views.loginAuth, name='loginAuth'),
		 url(r'^enquiries/$', views.view_enquiries, name='enquiries'),
       url(r'^enquire/$', views.add_lead, name='addLead'),
		 url(r'^followups/$', views.view_followups, name='followups'),
       url(r'^save_enquiry/$', views.save_enquiry, name='save_enquiry'),
       url(r'^followup/$', views.followup, name='followup'),
       url(r'^save_followup/$', views.save_followup, name='save_followup'),
       url(r'^search_enquiry/$', views.search_enquiry, name='search_enquiry'),
       url(r'^search_instructor/$', views.search_instructor, name='search_instructor'),
       url(r'^search_events/$', views.search_events, name='search_events'),
       url(r'^search_member/$', views.search_member, name='search_member'),
       url(r'^saveeventsubscribe/$', views.save_eventmembers, name='saveeventsubscribe'),
       url(r'^savecategories/$', views.save_studiocategories, name='savecategories'),
       url(r'^members/new/(?P<lead>\d+)/$', views.lead_to_member, name='lead_to_member'),
       url(r'^members/new/$', views.member_edit, name='member_add'),
       url(r'^members/edit/(?P<id>\d+)/$', views.member_edit, name='member_edit'),
       url(r'^members/delete/(?P<id>\d+)/$', views.member_delete, name='member_delete',),
       url(r'^instructors/new/$', views.instructor_edit, name='instructor_add'),
       url(r'^instructors/edit/(?P<id>\d+)/$', views.instructor_edit, name='instructor_edit'),
       url(r'^instructors/delete/(?P<id>\d+)/$', views.instructor_delete, name='instructor_delete'),
       url(r'^events/eventsubscribe/(?P<id>\d+)/$', views.view_eventmembers, name='event_members'),
       url(r'^lead/edit/(?P<id>\d+)/$', views.edit_lead, name='edit_lead'),
       url(r'^alerts/$', views.alerts, name='alerts'),
       url(r'^newmembers/$', views.new_members, name='new_members'),
       url(r'^newleads/$', views.new_leads, name='new_leads'),
       url(r'^newevents/$', views.new_events, name='new_events'),
       #url(r'^forgotpassword/$', views.forgotpassword, name='forgotpassword'),
       #url(r'^resetpassword/$', views.resetpassword, name='resetpassword'),
       url(r'^changepassword/$', views.change_password, name='changepassword'),
       url(r'^lead/convert/(?P<id>\d+)/$', views.convert_lead, name='convert_lead'),
       url(r'^api-token-auth/', obtain_auth_token),
       url(r'^loginApp/$', api_view.api_app_login, name='loginApp'),
       url(r'^validateToken/$', api_view.api_validate_token, name='validateToken'),
       url(r'^getleads/$', api_view.api_lead_list, name='getleads'),
       url(r'^getleadfollowups/$', api_view.api_single_lead, name='api_single_lead'),
       url(r'^getleadsCount/$', api_view.api_lead_count_view, name='getleadsCount'),
       url(r'^api_add_lead/$', api_view.api_add_lead, name='api_add_lead'),
       url(r'^api_add_followup/$', api_view.api_add_followup, name='api_add_followup'),
       url(r'^registration/$', api_view.registration, name='registration'),
       url(r'^user/password/reset/$','django.contrib.auth.views.password_reset',{'post_reset_redirect' : '/sway/user/password/reset/done/'},name="password_reset"),
       url(r'^user/password/reset/done/$','django.contrib.auth.views.password_reset_done'),
       url(r'^user/password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)$','django.contrib.auth.views.password_reset_confirm',{'post_reset_redirect' : '/sway/user/password/done/'},name="reset_confirm"),
       url(r'^user/password/done/$','django.contrib.auth.views.password_reset_complete'),
       url(r'^member/comments/(?P<Id>\d+)/$', views.member_comment, name='member_comment'),
       url(r'^member/comment/add/(?P<Id>\d+)/$', views.add_member_comment, name='add_member_comment'),
       url(r'^member/comment/save/$', views.save_member_comment, name='save_member_comment'),
       #url('^', include('django.contrib.auth.urls')),
       url('', include('social.apps.django_app.urls', namespace='social')),
       url('', include('django.contrib.auth.urls', namespace='auth')),
		)

sway/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models
from django.template.defaultfilters import default

from django.conf import settings
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token
from django.core import serializers
import json
from geoposition.fields import GeopositionField
from django.utils import timezone 

# A base model that alll other model shall extend
# THis model is abstract since this can't be instantiated an is a mean to keep all the common fields in one class
class BaseModel(models.Model):
    created_date = models.DateTimeField(default=timezone.now,blank=True)
    created_by =  models.ForeignKey(User,related_name='%(class)s_created_by',null=True,blank=True)
    modified_date = models.DateTimeField(null=True,default=timezone.now,auto_now=True)
    modified_by =   models.ForeignKey(User,related_name='%(class)s_modified_by',null=True,blank=True)
    class Meta:
        abstract = True
    def save(self, *args, **kwargs):
        modified_date = datetime.now()
        super(BaseModel, self).save(*args, **kwargs)

#from scipy.special.lambertw import __str__
class Studio(BaseModel):
    name = models.CharField(max_length = 128)
    area = models.CharField(max_length = 512,null=True,blank=True)
    email = models.EmailField(null=True,blank=True)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+91'. Up to 10 digits allowed.")
    mobile = models.CharField(validators=[phone_regex], blank=True, max_length=15)
    timezone = models.CharField(blank=True,max_length=40,null=True,default='Asia/Calcutta')
    description = models.CharField(max_length = 512,null=True,blank=True)
    short_description = models.CharField(max_length = 128,null=True,blank=True)
    searchable = models.BooleanField(default=False)
    def __unicode__(self):
            return self.name

class Document(models.Model):
    docfile = models.FileField(upload_to='documents/%Y/%m/%d')
    docname = models.CharField(max_length = 128, default='')
    studio = models.ForeignKey(Studio)
        

class TestLocation(BaseModel):
        positions = GeopositionField();
        def __unicode__(self):
            return str(self.id)

class StudioData(BaseModel):
    name = models.CharField(max_length = 128)
    description = models.CharField(max_length = 1024,null=True,blank=True)
    email = models.EmailField(null=True,blank=True)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+91'. Up to 10 digits allowed.")
    mobile = models.CharField(validators=[phone_regex], blank=True, max_length=15)
    def __unicode__(self):
            return self.name

class StudioDataMarker(BaseModel):
        longitude = models.DecimalField(max_digits=9, decimal_places=6, null=True,blank=True)
        latitude = models.DecimalField(max_digits=9, decimal_places=6,null=True,blank=True)
        studiodata = models.ForeignKey(StudioData)
        def __unicode__(self):
            return str(self.id)

class EventCategory(BaseModel):
        event_category_name = models.CharField(max_length = 128)
        studio = models.ForeignKey(Studio)
        def __unicode__(self):
            return self.event_category_name

class GlobalCategories(BaseModel):
        name = models.CharField(max_length = 128)
        ref_name = models.CharField(max_length = 128,null=True,blank=True)
        def __unicode__(self):
            return self.name    

class EntityCategories(BaseModel):
        category =  models.ForeignKey(GlobalCategories)
        studio = models.ForeignKey(Studio)
        def __unicode__(self):
            return str(self.id)

class GlobalCategoriesView(BaseModel):
        selected = models.BooleanField(default = False)
        categories = models.OneToOneField(GlobalCategories)
        class Meta:
            abstract = True

class Members(BaseModel):
        first_name = models.CharField(max_length=128)
        last_name = models.CharField(max_length=128)
        email = models.EmailField(null=True,blank=True)
        area = models.TextField()
        joining_date = models.DateField(null=True,blank=True)
        phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+91'. Up to 10 digits allowed.")
        mobile = models.CharField(validators=[phone_regex], blank=True, max_length=15)
        studio = models.ForeignKey(Studio)
        categories = models.ManyToManyField(EventCategory,blank=True,null=True,related_name="members")
        def __unicode__(self):
            return self.email

class MembersView(BaseModel):
        selected = models.BooleanField(default = False)
        member = models.OneToOneField(Members)
        class Meta:
            abstract = True
            
class EventType(BaseModel):
        event_type_name = models.CharField(max_length = 128)
        def __unicode__(self):
            return self.event_type_name
        
class EventLocations(BaseModel):
        event_location_name = models.CharField(max_length = 128)
        studio = models.ForeignKey(Studio, related_name="eventlocations")
        longitude = models.DecimalField(max_digits=9, decimal_places=6, null=True,blank=True)
        latitude = models.DecimalField(max_digits=9, decimal_places=6,null=True,blank=True)
        def __unicode__(self):
            return self.event_location_name
        
class UserActionLogs(BaseModel):
        description = models.CharField(max_length = 200)
        studio = models.ForeignKey(Studio)
        def __unicode__(self):
            return self.description

class Events(BaseModel):
        event_name = models.CharField(max_length=128)
        all_day= models.BooleanField(default=False)
        entity_category = models.ForeignKey(EntityCategories)
        event_location = models.ForeignKey(EventLocations, null=True)
        event_type = models.ForeignKey(EventType)
        
        start_date = models.DateField(default=datetime.now())
        end_date = models.DateField(default=datetime.now())
        
        start_time = models.TimeField(default='00:00')
        end_time = models.TimeField(default='00:00')
        studio = models.ForeignKey(Studio)
        
        def __unicode__(self):
            return self.event_name
        
        
class EventOccurence(BaseModel):
    events = models.OneToOneField(Events)
    frequency = models.IntegerField(default=0)
    wmd = models.IntegerField(default=0)
    eo_start_date = models.DateField(default=datetime.now())    
    eo_end_date = models.DateField(default=datetime.now())
    
    # adding following colomns for ui
    e_never = models.BooleanField(default=False)
    
    e_after = models.BooleanField(default=False)
    e_after_value = models.IntegerField(default=0)
    
    e_on = models.BooleanField(default=False)
    e_on_value = models.DateField(default=datetime.now())

    def __unicode__(self):
            return str(self.pk)

class EventMembers(BaseModel):
    event = models.ForeignKey(Events)
    member = models.ForeignKey(Members)
    def __unicode__(self):
            return u'%s' % (self.pk)
        
class Instructors(BaseModel):
    first_name = models.CharField(max_length = 128)
    last_name = models.CharField(max_length = 128)  
    email = models.CharField(max_length = 128)
    contact_number = models.CharField(max_length = 128)
    studio = models.ForeignKey(Studio)
    def __unicode__(self):
            return self.pk
    
class EventsInstructors(BaseModel):
    event_id = models.ForeignKey(Events)
    instructors_id = models.ForeignKey(Instructors)
    def __unicode__(self):
            return self.pk
        
class StudioUser(BaseModel):
    user = models.OneToOneField(User)
    studio_id = models.ForeignKey(Studio)    
    def __unicode__(self):
            return str(self.pk)
        
class ProductContacts(BaseModel):
    name = models.CharField(max_length = 128)
    email = models.CharField(max_length = 128)
    message = models.CharField(max_length = 1024)
    def __unicode__(self):
            return str(self.pk)
    

class Lead(BaseModel):    
    name =  models.CharField(max_length = 128)
    contact_detail = models.CharField(max_length = 255)
    email = models.CharField(max_length = 128)
    mobile = models.CharField(max_length = 128)
    nextfollowupdate = models.DateTimeField(default=None,null=True,blank=True)
    inquiryfor = models.CharField(max_length=255,null=True)
    studio = models.ForeignKey(Studio) 
    status = models.PositiveIntegerField(default=3)
    short_description = models.CharField(max_length=100,blank=True,null=True)
    def __unicode__(self):
            return str(self.pk)  
         

class LeadFollowUp(BaseModel):    
    lead = models.ForeignKey(Lead, related_name="followups")
    notes = models.CharField(max_length = 255)
    followed_by = models.ForeignKey(User)
    followed_date = models.DateField(auto_now_add=True) 
    def __unicode__(self):
            return str(self.pk)

class Comments(BaseModel):    
    studio = models.ForeignKey(Studio) 
    comment_notes = models.CharField(max_length = 255)
    comments_type = models.CharField(max_length = 255)
    comment_for = models.CharField(max_length = 255)
    def __unicode__(self):
            return str(self.pk)         


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

templates/sway/add_categories.html
{% extends "bs_base.html" %} {% load staticfiles %}
<!-- this for including anything in head tag -->
{% block head%}
<link href="{% static 'jquery/jquery.timepicker.css' %}"
	rel="stylesheet">
<link href="{% static 'jquery/jquery.datetimepicker.css' %}"
	rel="stylesheet">
<link href="{% static 'sway/css/forms.css' %}" rel="stylesheet">
<script src="{% static 'jquery/jquery.timepicker.js' %}"></script>
<script src="{% static 'jquery/jquery.datetimepicker.js' %}"></script>
{% endblock%}

<!-- all the content that will go into body tag -->
{% block container %}
<div id="form">
{% if id %}
<form action="{% url 'category_edit' id=id %}" class="form-horizontal"  method="POST" role="form">
{% else %}
<form action="{% url 'category_add' %}" class="form-horizontal" method="POST" role="form">
{% endif %}	

	{% csrf_token %}
	
{% if not form.event_category_name.errors %}
 <div class="form-group">
 	<label for="{{ form.event_category_name.id_for_label }}" class="col-sm-2 control-label">Category Name:</label>
 	<div class="col-sm-10">
    {{ form.event_category_name }}
    </div>
  </div>
 {% else %}
 <div class="row">
 	<p class="col-sm-2"></p>
 	<p class="col-sm-10 text-danger">{{ form.event_category_name.errors.as_text }}</p>
 </div>	
 <div class="form-group has-error">
   	<label for="{{ form.event_category_name.id_for_label }}" class="col-sm-2 control-label">Category Name:</label>
 	<div class="col-sm-10">
 	   {{ form.event_category_name }}
    </div>
 </div>
 {% endif %}
 
<div class="span7 text-center">
	<button type="submit" class="btn btn-primary" >Submit</button>
</div>

</form>
</div>
{% endblock %} 

templates/sway/add_events.html
{% extends "bs_base.html" %} {% load staticfiles %}
<!-- this for including anything in head tag -->
{% block head%}
<link href="{% static 'jquery/jquery.timepicker.css' %}"
	rel="stylesheet">
<link href="{% static 'jquery/jquery.datetimepicker.css' %}"
	rel="stylesheet">
<link href="{% static 'sway/css/forms.css' %}" rel="stylesheet">
<script src="{% static 'jquery/jquery.timepicker.js' %}"></script>
<script src="{% static 'jquery/jquery.datetimepicker.js' %}"></script>
{% endblock%}

<!-- all the content that will go into body tag -->
{% block container %}
<div id="form">
<form action="{% url 'saveevents'  %}" method="POST" role="form">
	{% csrf_token %}
	<div class="form-group">
		<div >
			{{ form.event_name.errors }} 
			<label for="{{ form.event_name.id_for_label }}">Event Name:</label>
				 {{ form.event_name }}
		</div>

		<div>
			{{ form.entity_category.errors }} <label
				for="{{ form.entity_category.id_for_label }}">Event Category:</label>
			{{ form.entity_category }}

			 {% for form in entity_category %}
        {% for field in form %}
            {{ field.label_tag }} {{ field }}
        {% endfor %}
    {% endfor %}
		</div>
		<div>
			{{ form.event_location.errors }} <label
				for="{{ form.event_location.id_for_label }}">Event Location:</label>
			{{ form.event_location }}
		</div>


		<div class="col">

			<table class=' table-condensed '>
				<tr>
					<td>
						<div class="form-group">
							{{ form.start_date.errors }} <label
								for="{{ form.start_date.id_for_label }}">Start Date:</label>
								 {{ form.start_date }}
						</div>
					</td>
					<td><div class="form-group">
							{{ form.start_time.errors }} <label for=" {{ form.start_time.id_for_label }} ">Start Time:</label> 
								{{ form.start_time }}
						</div></td>
				</tr>
				<tr>
					<td>
						<div class="form-group">
							{{ form.end_date.errors }} <label
								for="{{ form.end_date.id_for_label }}">End Date:</label>
								 {{form.end_date }}
						</div>
					</td>
					<td><div class="form-group">
							{{ form.end_time.errors }} <label
								for="{{ form.end_time.id_for_label }}">End Time:</label> 
								{{form.end_time }}
						</div></td>
				</tr>
			</table>

		</div>

		<div class="col">

			<table class=' table-condensed '>
				<tr>
					<td>
						<div>
							{{ form.all_day.errors }} <label
								for="{{ form.all_day.id_for_label }}">All Day:</label> {{form.all_day }}
						</div>
					</td>
					<td><div>
							{{ form.repeat.errors }} <label
								for="{{ form.repeat.id_for_label }}">Repeat:</label> {{form.repeat }}
						</div></td>
				</tr>
			</table>


		</div>

		<table>
			<tr>
				<td>
					<div style="margin-left: 16px; display: {% if not form.repeat.value %} none {%endif%}" class="form-group" id="repeatOptions">
						<table class="row">
							<tbody>
								<tr>
									<th><label for="{{ form.event_type.id_for_label }}">Repeat:</label></th>
									<td>{{ form.event_type.errors }} {{ form.event_type }}</td>
								</tr>
								<tr>
									<th></th>
									<td id="toreplace">
									<td>
								</tr>
								<tr>
									<th><label for="{{ form.never.id_for_label }}">Ends:</label></th>
									<td>
										<div>

											<table class='table'>
												{% for choice in form.never %}
												<tr>
													{% if choice.choice_value == '1' %}
													<td>{{ choice}}</td>
													<td></td> {% elif choice.choice_value == '2' %}
													<td>{{ choice}}</td>
													<td>{{ form.after.errors }}
													{{ form.after }}
													</td>
													 {% elif choice.choice_value == '3' %}
													<td>{{ choice}}</td>
													<td>{{ form.on.errors }}{{ form.on }}</td> 
													{% endif %}
												<tr>{% endfor %}
											</table>
										</div>
									</td>
								</tr>
							</tbody>
						</table>
					</div>
				</td>
			</tr>
			<tr>
				<td>
					<div id="weekly_repeat" style="margin-left: 16px; display: none">
						<table>
							<tr>
								<th><label for="{{ form.weeklyRepeat.id_for_label }}">
										Weekly:</label></th>
								<td>
									<table class='table'>
										<tr>
											{% for choice in form.weeklyRepeat %}
											<td>{{choice}}</td> {% endfor %}
										<tr>
									</table>
								</td>
							</tr>
						</table>
					</div>
				</td>
			</tr>
		</table>

		<div class="span7 text-center">
			<input type="submit" class="btn btn-primary" value="Save">
		</div>

	</div>

</form>
</div>
{% endblock %} {% block script %}

<!-- scripts for repeat event window -->
<script src="{% static 'events/events.js' %}"></script>


{% endblock%}

templates/sway/add_members.html
{% extends "bs_base.html" %}{% load staticfiles %}

{% block head%}
<link href="{% static 'bootstrap/css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet">
<link href="{% static 'sway/css/forms.css' %}" rel="stylesheet">
<script src="{% static 'bootstrap/js/jquery.js' %}"></script>   
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script> 
<script src="{% static 'bootstrap/js/moment.js' %}"></script> 	 	
<script src="{% static 'bootstrap/js/bootstrap-datetimepicker.js' %}"></script>
{% endblock%}

{% block container %}
<div id="form">
{% if id %}
<form action="{% url 'member_edit' id=id %}" class="form-horizontal"  method="POST" role="form">
{% elif lead %}
<form action="{% url 'lead_to_member' lead=lead %}" class="form-horizontal" method="POST" role="form">
{% else %}
<form action="{% url 'member_add' %}" class="form-horizontal" method="POST" role="form">
{% endif %}			

{% csrf_token %}

{% if not form.first_name.errors %}
 <div class="form-group">
 	<label for="{{ form.first_name.id_for_label }}" class="col-sm-2 control-label">First Name:</label>
 	<div class="col-sm-10">
    {{ form.first_name }}
    </div>
  </div>
 {% else %}
 <div class="row">
 	<p class="col-sm-2"></p>
 	<p class="col-sm-10 text-danger">{{ form.first_name.errors.as_text }}</p>
 </div>	
 <div class="form-group has-error">
   	<label for="{{ form.first_name.id_for_label }}" class="col-sm-2 control-label">First Name:</label>
 	<div class="col-sm-10">
 	   {{ form.first_name }}
    </div>
 </div>
 {% endif %}


{% if not form.last_name.errors %}
 <div class="form-group">
 	<label for="{{ form.last_name.id_for_label }}" class="col-sm-2 control-label">Last Name:</label>
 	<div class="col-sm-10">
    {{ form.last_name }}
    </div>
  </div>
 {% else %}
 <div class="row">
 	<p class="col-sm-2"></p>
 	<p class="col-sm-10 text-danger">{{ form.last_name.errors.as_text }}</p>
 </div>	
 <div class="form-group has-error">
   	<label for="{{ form.last_name.id_for_label }}" class="col-sm-2 control-label">Last Name:</label>
 	<div class="col-sm-10">
 	   {{ form.last_name }}
    </div>
 </div>
 {% endif %}

{% if not form.email.errors %}
 <div class="form-group">
 	<label for="{{ form.email.id_for_label }}" class="col-sm-2 control-label">Email:</label>
 	<div class="col-sm-10">
    {{ form.email }}
    </div>
  </div>
 {% else %}
 <div class="row">
 	<p class="col-sm-2"></p>
 	<p class="col-sm-10 text-danger">{{ form.email.errors.as_text }}</p>
 </div>	
 <div class="form-group has-error">
   	<label for="{{ form.email.id_for_label }}" class="col-sm-2 control-label">Email:</label>
 	<div class="col-sm-10">
 	   {{ form.email }}
    </div>
 </div>
 {% endif %}

 

{% if not form.area.errors %}
 <div class="form-group">
 	<label for="{{ form.area.id_for_label }}" class="col-sm-2 control-label">Address:</label>
 	<div class="col-sm-10">
    {{ form.area }}
    </div>
  </div>
 {% else %}
 <div class="row">
 	<p class="col-sm-2"></p>
 	<p class="col-sm-10 text-danger">{{ form.area.errors.as_text }}</p>
 </div>	
 <div class="form-group has-error">
   	<label for="{{ form.area.id_for_label }}" class="col-sm-2 control-label">Address:</label>
 	<div class="col-sm-10">
 	   {{ form.area }}
    </div>
 </div>
 {% endif %}

 


 {% if not form.mobile.errors %}
   <div class="form-group"> 
  <label for="{{ form.categories.id_for_label }}" class="col-sm-2 control-label">Mobile:</label>
    <div class='col-sm-10' >
      {{ form.mobile }}
                </div>
                 
  </div>
 {% else %}
 <div class="row">
  <p class="col-sm-2"></p>
  <p class="col-sm-10 text-danger">{{ form.mobile.errors.as_text }}</p>
 </div> 
  <div> 
  <label for="{{ form.categories.id_for_label }}" class="col-sm-2 control-label">Mobile:</label>
    <div class='col-sm-10' >
      {{ form.mobile }} 
    </div>
                 
  </div>
 
 {% endif %}



 {% if not form.joining_date.errors %}
   <div class="form-group"> 
  <label for="{{ form.categories.id_for_label }}" class="col-sm-2 control-label">Joining Date:</label>
    <div class='col-sm-10' >
      {{ form.joining_date }}
                </div>
                 
  </div>
 {% else %}
 <div class="row">
  <p class="col-sm-2"></p>
  <p class="col-sm-10 text-danger">{{ form.joining_date.errors.as_text }}</p>
 </div> 
  <div> 
  <label for="{{ form.categories.id_for_label }}" class="col-sm-2 control-label">Joining Date:</label>
    <div class='col-sm-10' >
      {{ form.joining_date }} 
    </div>
                 
  </div>
 
 {% endif %}

 
 {% if not form.categories.errors %}
   <div class="form-group"> 
  <label for="{{ form.categories.id_for_label }}" class="col-sm-2 control-label">Category:</label>
    <div class='col-sm-10' >
      {{ form.categories }}
                </div>
                 
  </div>
 {% else %}
 <div class="row">
  <p class="col-sm-2"></p>
  <p class="col-sm-10 text-danger">{{ form.categories.errors.as_text }}</p>
 </div> 
  <div> 
  <label for="{{ form.categories.id_for_label }}" class="col-sm-2 control-label">Category:</label>
    <div class='col-sm-10' >
      {{ form.categories }} 
    </div>
                 
  </div>
 
 {% endif %}



<div class="span7 text-center">
	<button type="submit" class="btn btn-primary" >Submit</button>
</div>
  <script type="text/javascript">
            $(function () {
                $('#id_joining_date').datetimepicker({
              
             pickTime: false
        });
            });
        </script> 
</form>
</div>
{% endblock %}